// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQ90GviU5WyWDRXArXjzuvZNLRRfORJw',
    appId: '1:776388841511:web:97453e00e34967f5fafe02',
    messagingSenderId: '776388841511',
    projectId: 'kothakhoj-322c5',
    authDomain: 'kothakhoj-322c5.firebaseapp.com',
    storageBucket: 'kothakhoj-322c5.firebasestorage.app',
    measurementId: 'G-S4KVNC2GJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBMkmzvj3azc4mBIoGxQ9cbL9yc2Mg5Qk',
    appId: '1:776388841511:android:92ee4c676ca9dd11fafe02',
    messagingSenderId: '776388841511',
    projectId: 'kothakhoj-322c5',
    storageBucket: 'kothakhoj-322c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4D0X8obAjFwwfnPoXw0dfMXI6QltcG-Y',
    appId: '1:776388841511:ios:17a1045855195c3efafe02',
    messagingSenderId: '776388841511',
    projectId: 'kothakhoj-322c5',
    storageBucket: 'kothakhoj-322c5.firebasestorage.app',
    iosClientId: '776388841511-k6mcpv6leeui34a2s5iqo8gae432a5vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.kothakhoj',
  );
}
