// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEnqNL8krhCEfFkuyXW3PrCmPeg5Sp85o',
    appId: '1:185746498577:web:8a1d51a4dae3539c55bdb0',
    messagingSenderId: '185746498577',
    projectId: 'mvproomrentandbook-ed049',
    authDomain: 'mvproomrentandbook-ed049.firebaseapp.com',
    storageBucket: 'mvproomrentandbook-ed049.firebasestorage.app',
    measurementId: 'G-R478L82F4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82N6GI712SMUFoGvLmniR-x1iJmT_9g0',
    appId: '1:185746498577:android:5a7921c0eb097f5455bdb0',
    messagingSenderId: '185746498577',
    projectId: 'mvproomrentandbook-ed049',
    storageBucket: 'mvproomrentandbook-ed049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdA91PXsDuk01IQ_rL-Ma4jYe6sfXbaaY',
    appId: '1:185746498577:ios:1708d4559577350155bdb0',
    messagingSenderId: '185746498577',
    projectId: 'mvproomrentandbook-ed049',
    storageBucket: 'mvproomrentandbook-ed049.firebasestorage.app',
    iosBundleId: 'com.example.mvproomrentandbook',
  );
}
